ProjetM2/Models/FILM.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetM2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        public int IDOBGET { get; set; }
        public string NAMEFILM { get; set; }
        public string DIRECTOR { get; set; }
        public Nullable<System.DateTime> DATESORTIE { get; set; }
        public string CATEGORIE { get; set; }
        public Nullable<bool> ENSTOCK { get; set; }
        public Nullable<int> LIST { get; set; }
        public Nullable<int> NBPRET { get; set; }
        public string PHOTO { get; set; }
    }
}

ProjetM2/Controllers/FilmController.cs
using ProjetM2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Data.Entity.Infrastructure;

namespace ProjetM2.Controllers
{
    public class FilmController : Controller
    {
        private ProjetM2Entities1 db = new ProjetM2Entities1();
        // GET: Film
        public ActionResult Index()
        {
            return View(db.FILM.ToList());
        }

        // GET: Film/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Film/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Film/Create
        [HttpPost]
        public ActionResult Create([Bind(Exclude ="IDOBJET")] FILM FilmToCreate)
        {
            if(!ModelState.IsValid)
                return View();
            try
            {
                db.FILM.Add(FilmToCreate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Photo(int id)
        {
            var Img = (from m in db.FILM where m.IDOBGET == id select m).First();
           // ViewData.Model = Img;
            return View(Img);
        }

        [HttpPost]
        public ActionResult Photo(FILM Img,HttpPostedFileBase files)
        {

            System.Diagnostics.Debug.WriteLine(Img.IDOBGET);

            string fileName = files.FileName;
            string extension = Path.GetExtension(fileName).ToLower();
            string dir = "../Images/";
            
            if (!Directory.Exists(Server.MapPath(dir)))
                   Directory.CreateDirectory(Server.MapPath(dir));
            
            if (extension.Equals(".jpg")|| extension.Equals(".png"))
            {
                
                string saveUrl = dir + fileName;
                files.SaveAs(Server.MapPath(saveUrl));
               

                //img.PHOTO= saveUrl;
                var img = new FILM {IDOBGET=16 , PHOTO = saveUrl};
                db.FILM.Attach(img);
                db.Entry(img).Property(x=>x.PHOTO).IsModified=true;
                db.SaveChanges();

            }
            
            return RedirectToAction("Index");
        }

        // GET: Film/Edit/5
        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var FilmToEdit = (from m in db.FILM where m.IDOBGET == id select m).First();

            if(FilmToEdit == null)
            {
                return HttpNotFound();
            }
            return View(FilmToEdit);
        }

        // POST: Film/Edit/5
        [HttpPost]
        public ActionResult Edit(FILM filmToEdit)
        {
            if (!ModelState.IsValid)
                return View();
            System.Diagnostics.Debug.WriteLine(filmToEdit.IDOBGET);
            try
            {
                // TODO: Add update logic here
                db.Entry(filmToEdit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                return View();
            }
        }

        // GET: Film/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            FILM course = db.FILM.Find(id);
            if(course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Film/Delete/5
        [HttpPost,ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // TODO: Add delete logic here
                FILM course = db.FILM.Find(id); 
                db.FILM.Remove(course);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //search by filmname categorie ou director
        public ActionResult Search(string keyword, bool? done, bool? done1, bool? done2)
        {

            var work = from t in db.FILM select t;

            if (done.Value)
            {
                work = work.Where(t => t.NAMEFILM.Contains(keyword));
            }

            if (done1.Value)
            {
                work = work.Where(t => t.DIRECTOR.Contains(keyword));
            }

            if (done2.Value)
            {
                work = work.Where(t => t.CATEGORIE.Contains(keyword));
            }



            //System.Diagnostics.Debug.WriteLine(work.GetType());//afficher le resultat dans le console

            return View(work);

        }
    }
}

ProjetM2/Controllers/LouerController.cs
using ProjetM2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using Microsoft.Ajax.Utilities;
using System.Runtime.Remoting.Contexts;
using System.Runtime.InteropServices;
using System.IO;
using iText.Kernel.Pdf;
using iText.Kernel.Geom;
using iText.Html2pdf;
using Org.BouncyCastle.Asn1.Cms;
using System.Windows.Forms;

namespace ProjetM2.Controllers
{
    
    public class LouerController : Controller
    {
        private ProjetM2Entities1 db = new ProjetM2Entities1();
        // GET: Louer
        public ActionResult Index()
        {
            return View(db.FILM.OrderByDescending(FILM => FILM.NBPRET).Take(10));
        }
        public ActionResult Index2()
        {
            return View(db.FILM.ToList());
        }


        // GET: Louer
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var FilmToLouer = (from m in db.FILM where m.IDOBGET == id select m).First();
            

            if (FilmToLouer == null)
            {
                return HttpNotFound();
            }
            return View(FilmToLouer);
        }

        // POST: Louer
        [HttpPost]
        public ActionResult Edit(FILM f) 
        { 
            if (!ModelState.IsValid)
                    return View();
            try
             {
                string client = Session["CLIENT"].ToString();
                int clientID;
                Int32.TryParse(client, out clientID);
                CLIENT cl = db.CLIENT.Find(clientID);
                FILM fl = db.FILM.Find(f.IDOBGET);
                if (   fl.LIST > 0)
                {
                    cl.LISTLOUEE = null;
                    cl.TIMERENDU = null;
                    fl.LIST--;
                    fl.NBPRET++;
                    cl.LISTLOUEE = fl.NAMEFILM;
                    cl.TIMELOUEE = DateTime.Now;
                    db.SaveChanges();



                    MessageBox.Show("Réussir");
                    return RedirectToAction("Index");
                   

                }
                else
                {
                    MessageBox.Show("Non Réussir");
                    return RedirectToAction("Index");
                    

                }
            }
            catch(Exception ex)
                  {
                        return View();
                  }
        }
        public ActionResult Search(string keyword, bool? done , bool?done1 , bool?done2)
        {
           
            var work = from t in db.FILM select t;

            if (done.Value)
            {
                work = work.Where(t => t.NAMEFILM.Contains(keyword));
            }

            if (done1.Value)
            {
                work = work.Where(t => t.DIRECTOR.Contains(keyword));
            }

            if (done2.Value)
            {
                work = work.Where(t => t.CATEGORIE.Contains(keyword));
            }



            //System.Diagnostics.Debug.WriteLine(work.GetType());//afficher le resultat dans le console

            return View(work);

        }

        public ActionResult Rendre()
        {
            string client = Session["CLIENT"].ToString();
            int clientID;
            Int32.TryParse(client, out clientID);
            CLIENT cl = db.CLIENT.Find(clientID);
           
            if(cl.LISTLOUEE == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                string filmLouee = cl.LISTLOUEE;
               
                FILM fl = db.FILM
                            .Where(b => b.NAMEFILM == filmLouee)
                            .FirstOrDefault();
                
                fl.LIST += 1;
                cl.TIMERENDU = DateTime.Now;
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
        }

        public ActionResult Facture()
        {
            string client = Session["CLIENT"].ToString();
            int clientID;
            Int32.TryParse(client, out clientID);
            CLIENT cl = db.CLIENT.Find(clientID);

            if (cl.LISTLOUEE == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(db.CLIENT.Where(p => p.IDOBGET == clientID).ToList());
            }
        }

    }
}

ProjetM2/Views/Film/Create.cshtml
@model ProjetM2.Models.FILM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>FILM</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.NAMEFILM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NAMEFILM, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NAMEFILM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DIRECTOR, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DIRECTOR, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DIRECTOR, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DATESORTIE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DATESORTIE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DATESORTIE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CATEGORIE, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CATEGORIE, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CATEGORIE, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ENSTOCK, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ENSTOCK, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ENSTOCK, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LIST, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LIST, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LIST, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NBPRET, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NBPRET, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NBPRET, "", new { @class = "text-danger" })
        </div>
    </div>

   

    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetM2/Views/Film/Delete.cshtml
@model ProjetM2.Models.FILM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FILM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDOBGET)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDOBGET)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NAMEFILM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAMEFILM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DIRECTOR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DIRECTOR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATESORTIE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATESORTIE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORIE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ENSTOCK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ENSTOCK)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LIST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LIST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NBPRET)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NBPRET)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PHOTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PHOTO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjetM2/Views/Film/Edit.cshtml
@model ProjetM2.Models.FILM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FILM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDOBGET)
       
        <div class="form-group">
            @Html.LabelFor(model => model.NAMEFILM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NAMEFILM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NAMEFILM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DIRECTOR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIRECTOR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIRECTOR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATESORTIE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATESORTIE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATESORTIE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CATEGORIE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CATEGORIE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CATEGORIE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ENSTOCK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ENSTOCK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ENSTOCK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LIST, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LIST, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LIST, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NBPRET, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NBPRET, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NBPRET, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetM2/Views/Film/Index.cshtml
@model IEnumerable<ProjetM2.Models.FILM>

@{
    Layout = null;

}
@using (Html.BeginForm("Search", "Louer", FormMethod.Get, new { @class = "form-inline" }))
{
    @Html.Label("keyword", "Search : ", new { @class = "control-label" })
    @Html.TextBox("keyword", null, new { @class = "form-control" })
    @Html.Label("done", "film name", new { @class = "control-label" })
    @Html.CheckBox("done")
    @Html.Label("done1", "director", new { @class = "control-label" })
    @Html.CheckBox("done1")
    @Html.Label("done2", "categorie", new { @class = "control-label" })
    @Html.CheckBox("done2")
    <input type="submit" value="SUMBIT" class="btn btn-info" />
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <a href="/Film/Create">Creér une film</a>
    <a href="/Home/Index">Clients infos</a>
    <a href="/Client/Login">Déconnexion</a>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IDOBGET)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NAMEFILM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DIRECTOR)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DATESORTIE)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CATEGORIE)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ENSTOCK)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LIST)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NBPRET)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PHOTO)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IDOBGET)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NAMEFILM)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DIRECTOR)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DATESORTIE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CATEGORIE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ENSTOCK)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LIST)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NBPRET)
                </td>
                <td>
                   
                    <img style="width:50px;height:50px" src="@Html.DisplayFor(modelItem => item.PHOTO)" alt="" />

                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.IDOBGET }) |
                    @Html.ActionLink("Add photo", "Photo", new { id = item.IDOBGET }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.IDOBGET })
                </td>
            </tr>
        }

    </table>
</body>
</html>

ProjetM2/Views/Film/Photo.cshtml
@model ProjetM2.Models.FILM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UpdatePhoto</title>
</head>
<body>
    <div>

        
        <form action="/Film/Photo" method="post" enctype="multipart/form-data">
            <p>
                <label for="file">ajouter un photo : </label>
                <input type="file" name="files" id="file" class="form-control" />
            </p>
            <p>
                <input type="submit" value="save" class="btn-info" />
            </p>


        </form>
    </div>
</body>
</html>

ProjetM2/Views/Film/Search.cshtml
@model IEnumerable<ProjetM2.Models.FILM>

@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDOBGET)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NAMEFILM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DIRECTOR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATESORTIE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CATEGORIE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ENSTOCK)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LIST)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NBPRET)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PHOTO)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDOBGET)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NAMEFILM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DIRECTOR)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DATESORTIE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CATEGORIE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ENSTOCK)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LIST)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NBPRET)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PHOTO)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.IDOBGET }) |
            |
            @Html.ActionLink("Delete", "Delete", new { id = item.IDOBGET })
        </td>
        
    </tr>
}

</table>